Rname: mit-ronin-conda-2022a
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - aiohttp=3.8.1
  - aiosignal=1.2.0
  - anyio=2.2.0
  - argon2-cffi=20.1.0
  - asciitree=0.3.3
  - async-timeout=4.0.1
  - async_generator=1.10
  - attrs=21.4.0
  - babel=2.9.1
  - backcall=0.2.0
  - blas=1.0
  - bleach=4.1.0
  - bokeh=2.4.2
  - boto3=1.18.21
  - botocore=1.21.41
  - bottleneck=1.3.2
  - brotlipy=0.7.0
  - c-ares=1.18.1
  - ca-certificates=2021.10.26
  - cachetools=4.2.2
  - cairo=1.14.12
  - cartopy=0.18.0
  - certifi=2021.10.8
  - cffi=1.14.6
  - cftime=1.5.1.1
  - chardet=4.0.0
  - charset-normalizer=2.0.4
  - click=8.0.3
  - cloudpickle=2.0.0
  - cryptography=36.0.0
  - curl=7.80.0
  - cycler=0.11.0
  - cytoolz=0.11.0
  - dask=2021.7.1
  - dask-core=2021.7.1
  - debugpy=1.5.1
  - decorator=5.1.0
  - defusedxml=0.7.1
  - distributed=2021.7.1
  - entrypoints=0.3
  - expat=2.2.10
  - fasteners=0.16.3
  - fontconfig=2.13.0
  - freetype=2.11.0
  - fribidi=1.0.10
  - frozenlist=1.2.0
  - fsspec=2022.1.0
  - geos=3.8.0
  - gettext=0.19.8.1
  - giflib=5.2.1
  - glib=2.56.2
  - graphite2=1.3.14
  - graphviz=2.40.1
  - harfbuzz=1.8.8
  - hdf4=4.2.13
  - hdf5=1.10.6
  - heapdict=1.0.1
  - icu=58.2
  - idna=2.10
  - importlib-metadata=4.8.2
  - importlib_metadata=4.8.2
  - intel-openmp=2021.4.0
  - ipykernel=6.4.1
  - ipython=7.29.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - jedi=0.18.0
  - jinja2=3.0.2
  - jmespath=0.10.0
  - jpeg=9d
  - json5=0.9.6
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=7.1.0
  - jupyter_console=6.4.0
  - jupyter_core=4.9.1
  - jupyter_server=1.4.1
  - jupyterlab=3.1.7
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.10.2
  - jupyterlab_widgets=1.0.0
  - kiwisolver=1.3.1
  - krb5=1.19.2
  - lcms2=2.12
  - libcurl=7.80.0
  - libcxx=12.0.0
  - libedit=3.1.20210910
  - libev=4.33
  - libffi=3.3
  - libgfortran
  - libiconv=1.16
  - libnetcdf=4.6.1
  - libnghttp2=1.46.0
  - libpng=1.6.37
  - libsodium=1.0.18
  - libssh2=1.9.0
  - libtiff=4.2.0
  - libwebp=1.2.0
  - libwebp-base=1.2.0
  - libxml2=2.9.10
  - locket=0.2.1
  - lz4-c=1.9.3
  - markupsafe=2.0.1
  - matplotlib=3.3.4
  - matplotlib-base=3.3.4
  - matplotlib-inline=0.1.2
  - mistune=0.8.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - msgpack-python=1.0.2
  - multidict=5.2.0
  - nbclassic=0.2.6
  - nbclient=0.5.3
  - nbconvert=6.3.0
  - nbformat=5.1.3
  - ncurses=6.3
  - nest-asyncio=1.5.1
  - netcdf4=1.5.7
  - notebook=6.4.6
  - numcodecs=0.9.1
  - numexpr=2.8.1
  - numpy=1.20.3
  - numpy-base=1.20.3
  - olefile=0.46
  - openssl=1.1.1m
  - packaging=21.3
  - pandas=1.3.5
  - pandocfilters=1.4.3
  - pango=1.42.4
  - parso=0.8.3
  - partd=1.2.0
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.4.0
  - pip=21.2.4
  - pixman=0.40.0
  - proj=6.2.1
  - prometheus_client=0.12.0
  - prompt-toolkit=3.0.20
  - prompt_toolkit=3.0.20
  - psutil=5.8.0
  - ptyprocess=0.7.0
  - pycparser=2.21
  - pygments=2.10.0
  - pyopenssl=21.0.0
  - pyparsing=3.0.4
  - pyqt=5.9.2
  - pyrsistent=0.18.0
  - pyshp=2.1.3
  - pysocks=1.7.1
  - python=3.9.2
  - python-dateutil=2.8.2
  - python-graphviz=0.16
  - python_abi=3.9
  - pytz=2021.3
  - pyyaml=6.0
  - pyzmq=22.3.0
  - qt=5.9.7
  - qtconsole=5.1.1
  - qtpy=1.10.0
  - readline=8.1.2
  - requests=2.27.1
  - s3fs=0.4.2
  - s3transfer=0.5.0
  - scipy=1.7.3
  - send2trash=1.8.0
  - setuptools=58.0.4
  - shapely=1.7.1
  - sip=4.19.13
  - six=1.16.0
  - sniffio=1.2.0
  - sortedcontainers=2.4.0
  - sqlite=3.37.0
  - tblib=1.7.0
  - terminado=0.9.4
  - testpath=0.5.0
  - tk=8.6.11
  - toolz=0.11.2
  - tornado=6.1
  - traitlets=5.1.1
  - typing-extensions=3.10.0.2
  - typing_extensions=3.10.0.2
  - tzdata=2021e
  - urllib3=1.26.7
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.37.1
  - widgetsnbextension=3.5.1
  - xarray=0.18.0
  - xmitgcm=0.5.1
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.6.3
  - zarr=2.8.1
  - zeromq=4.3.4
  - zict=2.0.0
  - zipp=3.7.0
  - zlib=1.2.11
  - zstd=1.4.9
